### ISSUE TITLE
Kar layout issue?

### ISSUE THREAD

**Issue by yrashk** [lburgazzoli/gradle-karaf-plugin#11]
I am not entirely sure about this issue, but while having a problem installing a KAR generated with this plugin (thanks for developing it, by the way!), I encountered the following fact.

If you look at https://karaf.apache.org/manual/latest/users-guide/kar.html it suggests that the KAR follows Maven repo structure, for example

```
    48049  2013-12-06 10:52   repository/javax/portlet/portlet-api/2.0/portlet-api-2.0.jar
```

Where groupId `java.portlet` is resolved to `javax/portlet'. Now, when I look into the exploded kar, I see this:

```
drwxr-xr-x   3 yrashk  staff   102 21 Mar 05:56 javax.servlet
```

Is there anything I am missing?

P.S. The problem I am having with this KAR deployment is that it complains about not being able to install my application's artifacts (can't locate them). So I figured if they are not in the expected format of `[com/project]/[artifactId]/[version]` then there's no surprise it can't find them.

What if we replaced dots with slashes here

https://github.com/lburgazzoli/gradle-karaf-plugin/blob/master/src/main/groovy/com/github/lburgazzoli/gradle/plugin/karaf/kar/KarafKarTask.groovy#L64

and here

https://github.com/lburgazzoli/gradle-karaf-plugin/blob/master/src/main/groovy/com/github/lburgazzoli/gradle/plugin/karaf/kar/KarafKarTask.groovy#L75

Do you think that'd be appropriate? Or am I missing something indeed?

**Comment by yrashk** [comment]
So I went ahead and put your plugin into buildSrc to play with it. The problem I mentioned above got resolved with the proposed change. The change so far is:

```diff
diff --git a/src/main/groovy/com/github/lburgazzoli/gradle/plugin/karaf/kar/KarafKarTask.groovy b/src/main/groovy/com/github/lburgazzoli/gradle/plugin/karaf/kar/KarafKarTask.groovy
index 57a8a91..068145d 100644
--- a/src/main/groovy/com/github/lburgazzoli/gradle/plugin/karaf/kar/KarafKarTask.groovy
+++ b/src/main/groovy/com/github/lburgazzoli/gradle/plugin/karaf/kar/KarafKarTask.groovy
@@ -61,7 +61,7 @@ class KarafKarTask extends Jar {
                     it.file.toPath(),
                     asKarPath(
                         rootPath,
-                        "${it.group}/${it.name}/${it.version}",
+                        "${it.group.replaceAll("\\.", "/")}/${it.name}/${it.version}",
                         "${it.name}-${it.version}.${it.type}"
                     )
                 )
@@ -72,7 +72,7 @@ class KarafKarTask extends Jar {
             features.outputPath,
             asKarPath(
                 rootPath,
-                "${features.project.group}/${features.name}/${features.project.version}",
+                "${features.project.group.replaceAll("\\.", "/")}/${features.name}/${features.project.version}",
                 "${features.name}-${features.project.version}.xml"
             )
         )
```

I am still running into another issue which is likely unrelated.

**Comment by lburgazzoli** [comment]
Can you submit a PR ?

**Comment by yrashk** [comment]
I sure can! As soon as I am done investigating that other problem (it might still be *somewhat* related), I will submit a PR.

**Comment by lburgazzoli** [comment]
I'd really appreciate your effors

**Comment by yrashk** [comment]
I submitted #12 but I am still fighting another issue. One of my dependencies' dependency, even though properly included into the kar, is giving an error:

```
missing requirement [project/1.0.0.SNAPSHOT] osgi.identity; osgi.identity=de.javakaffee.kryo-serializers; type=osgi.bundle; version="[0.28.0,0.28.0]"; resolution:=mandatory [caused by: Unable to resolve de.javakaffee.kryo-serializers/0.28.0: missing requirement [de.javakaffee.kryo-serializers/0.28.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.esotericsoftware.kryo)(version>=2.24.0)(!(version>=3.0.0)))"]]
```

I am not quite sure what's happening there :-(

**Comment by lburgazzoli** [comment]
any change to get the full build.gradle ?

**Comment by yrashk** [comment]
I think I have a clue. de.javakaffee.kryo-serializers/0.28.0 has a strict requirement for com.esotericsoftware.kryo (in their MANIFEST.MF)

```
com.esotericsoftware.kryo;version="[2.24.0,3.0)"
```

Yet another library that I use requires

```xml
<dependency>
            <groupId>com.esotericsoftware</groupId>
            <artifactId>kryo</artifactId>
            <version>3.0.0</version>
</dependency>
```

Which is excluded in the above. Will try to figure this out, but from the looks of it, it's unrelated to this plugin.

**Comment by lburgazzoli** [comment]
Great, if you ahve any issue let me now and again, PRs are more than welcome

**Comment by yrashk** [comment]
For the record (if anybody google finds this issue), the above problem can seemingly be fixed with this in build.grade:

```groovy
configurations.all {
    resolutionStrategy {
        force 'com.esotericsoftware:kryo:3.0.3', 'de.javakaffee:kryo-serializers:0.37'
    }
}
```

Now, the last issue I am fighting is that after a successful installation, my feature appears twice in `feature:list -i`. @lburgazzoli have you ever seen something like this or have an idea why that might be the case?

**Comment by lburgazzoli** [comment]
Have you un-installed the feature before ?

**Comment by yrashk** [comment]
Ok, the double installation got resolved, too. Apparently I had holahub repo listed twice after initial failed attempts.

**Comment by lburgazzoli** [comment]
yep that could happen
