### ISSUE TITLE
KAR not being properly updated?

### ISSUE THREAD

**Issue by yrashk** [lburgazzoli/gradle-karaf-plugin#15]
I just found out that the plugin might not be updating the KAR file properly.

Imagine I had one KAR build done:

```
➜  build git:(master) ✗ ls -la karaf/kar/project-1.0.0-SNAPSHOT.kar
-rw-r--r--  1 yrashk  staff  18159730 21 Mar 10:48 karaf/kar/project-1.0.0-SNAPSHOT.kar
```

Then I changed one source file, regenerated KAR (gradle generateKar) and we can
see that the timestamp has changed, but the size didn't:

```
➜  build git:(master) ✗ ls -la karaf/kar/project-1.0.0-SNAPSHOT.kar
-rw-r--r--  1 yrashk  staff  18159730 21 Mar 10:51 karaf/kar/project-1.0.0-SNAPSHOT.kar
```

Now, if I clean it up:

```
➜  build git:(master) ✗ rm -rf karaf
```

And rebuild it again, then the file is new:

```
➜  build git:(master) ✗ ls -la karaf/kar/project-1.0.0-SNAPSHOT.kar
-rw-r--r--  1 yrashk  staff  18159783 21 Mar 10:51 karaf/kar/project-1.0.0-SNAPSHOT.kar
```

**Comment by lburgazzoli** [comment]
I did something similar, and that's strange as if you look at the gradle report it shows that the module2 (the  one I've changed) has been rebuilt so the kar should have been amended as well:

```
$ gradle assemble
:module1:compileJava UP-TO-DATE
:module1:processResources UP-TO-DATE
:module1:classes UP-TO-DATE
:module1:jar UP-TO-DATE
:module2:compileJava
:module2:processResources UP-TO-DATE
:module2:classes
:module2:jar
:features:generateFeatures
:features:generateKar
:features:compileJava UP-TO-DATE
:features:processResources UP-TO-DATE
:features:classes UP-TO-DATE
:features:war UP-TO-DATE
:features:assemble
:module1:assemble UP-TO-DATE
:module2:war
:module2:assemble
```

I need to investigate a little bit more

**Comment by yrashk** [comment]
May be the jar was updated but your plugin somehow didn't pick up changed
jar file somehow? Just spitballing... happy to help, this is a minor but
annoying issue :)

On Tue, Mar 22, 2016 at 12:34 AM, Luca Burgazzoli <notifications@github.com>
wrote:

> I did something similar, and that's strange as if you look at the gradle
> report it shows that the module2 (the one I've changed) has been rebuilt so
> the kar should have been amended as well:
>
> $ gradle assemble
> :module1:compileJava UP-TO-DATE
> :module1:processResources UP-TO-DATE
> :module1:classes UP-TO-DATE
> :module1:jar UP-TO-DATE
> :module2:compileJava
> :module2:processResources UP-TO-DATE
> :module2:classes
> :module2:jar
> :features:generateFeatures
> :features:generateKar
> :features:compileJava UP-TO-DATE
> :features:processResources UP-TO-DATE
> :features:classes UP-TO-DATE
> :features:war UP-TO-DATE
> :features:assemble
> :module1:assemble UP-TO-DATE
> :module2:war
> :module2:assemble
>
> I need to investigate a little bit more
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lburgazzoli/gradle-karaf-plugin/issues/15#issuecomment-199680151>
>



-- 
Y.

**Comment by lburgazzoli** [comment]
v0.0.20 released

**Comment by yrashk** [comment]
Thanks a lot!!

On Wed, Mar 23, 2016 at 9:18 AM, Luca Burgazzoli <notifications@github.com>
wrote:

> v0.0.20 released
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lburgazzoli/gradle-karaf-plugin/issues/15#issuecomment-200419657>
>



-- 
Y.
