### ISSUE TITLE
Allow customization of kar file name

### ISSUE THREAD

**Issue by jvz** [lburgazzoli/gradle-karaf-plugin#16]
In the java plugin, I can set `jar.archiveName = 'foo.jar'` to override the default artifact name. I'd like to be able to do the same with kar files. Right now, I just have a Copy task that renames the file:

```groovy
task renameKar(type: Copy) {
	from "build/karaf/kar/${project.name}-${project.version}.kar"
	into "build/karaf/kar/"
	rename "${project.name}-${project.version}.kar", "${project.name}.kar"
}
```

**Comment by lburgazzoli** [comment]
From v0.0.21 :

```
    kar {   
        archiveName = 'mykar'
    }
```

**Comment by jvz** [comment]
Thanks again!

**Comment by jvz** [comment]
Notes to self (and others):

```
karaf {
  kar {
    archiveName = 'foo'
  }
}
```

And the .kar extension is automatically appended.
