### ISSUE TITLE
Adding bundle instructions in the features

### ISSUE THREAD

**Issue by yrashk** [lburgazzoli/gradle-karaf-plugin#19]
I have a transitive dependency that results in a bundle line like this:

```xml
    <bundle>wrap:mvn:org.bitcoinj/bitcoinj-core/0.13.6</bundle>
```

However, since it is not an OSGi package, and I [desperately] need to attach a fragment to it, I need to assign a symbolic name to it, like this:

```xml
    <bundle>wrap:mvn:org.bitcoinj/bitcoinj-core/0.13.6$Bundle-SymbolicName=bitcoinj</bundle>
```

However, I can't quite figure out how this should be done with this plugin.

I tried different variations of this but none worked:

```groovy
bundle('wrap:mvn:org.bitcoinj/bitcoinj-core/0.13.6') {
    it.instruction "Bundle-SymbolicName", "bitcoinj"
}
```

Any advice? Thanks!

**Comment by lburgazzoli** [comment]
this:

```groovy
bundle ('org.bitcoinj:bitcoinj-core') {
    wrap = true
    instruction 'Bundle-SymbolicName', 'bitcoinj'
}
```

Should do the trick

**Comment by yrashk** [comment]
It did! Thanks, that was a lifesaver! :) Eventually, I will be happy to help you writing some really good docs on this plugin.

**Comment by yrashk** [comment]
I suspect that it is still a tad wrong, however. The separator for instructions should be a dollar sign ($), not  a question mark, unless there's something else going on in that area.

**Comment by yrashk** [comment]
See this https://ops4j1.jira.com/wiki/display/paxurl/Wrap+Protocol

Thoughts?

**Comment by lburgazzoli** [comment]
Adding doc would be really appreciated ;)

**Comment by lburgazzoli** [comment]
and btw, the wrap = true might be redundant
