### ISSUE TITLE
<configfile /> element generation is invalid for Karaf 4

### ISSUE THREAD

**Issue by protenhan** [lburgazzoli/gradle-karaf-plugin#26]
When generating a <configfile /> element into the feature xml the generated xml contains an attribute that is named ```"filename="foo/bar"```. However, the attribute must be named ```finalname="foo/bar```.

See also the http://www-eu.apache.org/dist/karaf/documentation/4_x.html#Featureconfigurationfiles

**Comment by lburgazzoli** [comment]
Should be fixed in v0.0.41

**Comment by protenhan** [comment]
Thank you for the quick fix 👍
