### ISSUE TITLE
MvnProtocolParser.groovy

### ISSUE THREAD

**Issue by niclash** [lburgazzoli/gradle-karaf-plugin#27]
Karaf gets its MVN protocol from "Pax URL" project, and perhaps you investigate how to leverage that library to get the full scope of URL support that Karaf has.

See https://ops4j1.jira.com/wiki/display/paxurl/Mvn+Protocol for "mvn" protocol and https://ops4j1.jira.com/wiki/display/paxurl/Documentation for all the gory details.

**Comment by lburgazzoli** [comment]
Can you tell me what would be a use case ?

**Comment by niclash** [comment]
Not really, what I noticed is that you try to parse mvn: protocol, which Karaf also understands, but it is probably not doing the same thing. By using Pax URL, you will get the same result.

**Comment by niclash** [comment]
I view this as a "suggestion", nothing more.

**Comment by lburgazzoli** [comment]
Yep I will have a look.
I've explored a number of option but every one was too much for the use case

**Comment by lburgazzoli** [comment]
Done in 0.0.42, can you check it does not break your build ? :)

**Comment by niclash** [comment]
The existing project generated the identical Karaf Features repository (~2300 lines worth).

**Comment by lburgazzoli** [comment]
Great, thx for the suggestion

**Comment by niclash** [comment]
Unfortunately, I have forgotten why I was looking at this in the first place, probably to add support for OSGi directives into wrap: protocol.
