### ISSUE TITLE
Support for excluding specific bundles

### ISSUE THREAD

**Issue by mbelling** [lburgazzoli/gradle-karaf-plugin#28]
Occasionally I will depend on two libraries that through their transitive dependencies will include bundles with conflicting exports.  In the old gradle karaf features plugin there was the ability to define a bundle with 'include=false' in order to not include the bundle, which I would use for the transitive dependency that I did not want included in the feature.  Is there a way to do the same in this plugin?

`bundle('someBundleName') {
    include = false
}`

**Comment by lburgazzoli** [comment]
I have decide to leverage gradle's features as much as possible so if you want to exclude a dependency, you should do it using gradle configurations, like:

```groovy
configurations {
    karaf {
        extendsFrom compile
        exclude group: 'org.apache.servicemix.bundles', module: 'org.apache.servicemix.bundles.javax-cache-api'
    }
}

dependencies {
    compile 'org.slf4j:slf4j-simple:1.7.21'
    compile 'org.apache.camel:camel-jcache:2.17.3'
}

karaf {
    features {
        name        = 'my-camel-jcache'
        description = 'my-camel-jcache'
        configurations 'karaf'
    }
}
```

**Comment by mbelling** [comment]
That makes sense, thank you.
