### ISSUE TITLE
Add support to upload features.xml to maven repository

### ISSUE THREAD

**Issue by dixiesraj** [lburgazzoli/gradle-karaf-plugin#30]
Hello,
First, **Great job!!!** with this plugin. Saved so much of time and learnt things can be made better than what I have.

On the request, is there a way to upload the generated features xml on to a mvn respository similar to karaf-maven plugin?

~Dixie.

**Comment by lburgazzoli** [comment]
It should be possible but it should do it already as the generated feature is added to the archives to install, it it possible to have a sample of what you use to upload your project to the repo ?

**Comment by yrashk** [comment]
I use Gradle's maven publishing to publish features, seems to be sufficient!

**Comment by lburgazzoli** [comment]
@yrashk do you have any specific config to make it working ? or does it work out of the box ?

**Comment by yrashk** [comment]
I'll check later today or tomorrow when I get to my computer

**Comment by yrashk** [comment]
So this is basically what I do:

```groovy
apply plugin: 'maven'
apply plugin: 'maven-publish'

publishing {
    publications {
        Publication(MavenPublication) {
            groupId rootProject.group
            artifactId rootProject.name
            artifact("${rootProject.buildDir}/karaf/features/${rootProject.name}-${rootProject.version}-features.xml") {
                classifier "features"
            }
        }
    }
}
```

Does this help at all?

**Comment by dixiesraj** [comment]
@yrashk Awesome. I did it the same way using publishing then used uploadArchives task like this

```groovy
 uploadArchives {
        repositories {
            mavenDeployer {
                repository(url: nexusReleaseRepoURL) {
                    authentication(userName: nexusUsername, password: nexusPassword)
                }
....
```

**Comment by lburgazzoli** [comment]
@dixiesraj  does it work ?

**Comment by dixiesraj** [comment]
@lburgazzoli Yes it works. Thanks again.

**Comment by lburgazzoli** [comment]
great
