### ISSUE TITLE
Differently classified dependencies get conflated

### ISSUE THREAD

**Issue by yrashk** [lburgazzoli/gradle-karaf-plugin#32]
I have these dependencies:

```
    compile "ca.uhn.hapi.fhir:hapi-fhir-testpage-overlay:2.0:classes"
    runtime "ca.uhn.hapi.fhir:hapi-fhir-testpage-overlay:2.0@war"
```

However, in features they get conflated into one:

```
wrap:mvn:ca.uhn.hapi.fhir/hapi-fhir-testpage-overlay/2.0
```

Is there anything that can be done about this?

**Comment by lburgazzoli** [comment]
smells like a bug, I think I need to add  more fields for hash/equality check.

**Comment by yrashk** [comment]
By the way, there's also an additional issue here:

the plugin will generate 

```
<bundle>wrap:mvn:ca.uhn.hapi.fhir/hapi-fhir-testpage-overlay/2.0</bundle>
```

however, because of the `classifier` type it should generate

```
<bundle>wrap:mvn:ca.uhn.hapi.fhir/hapi-fhir-testpage-overlay/2.0/jar/classes</bundle>
```

Failure to do so results in `Could not find artifact ca.uhn.hapi.fhir:hapi-fhir-testpage-overlay:jar:2.0`

**Comment by lburgazzoli** [comment]
If you have time, can you send a PR with a failing example ? 
I can have a look later today

**Comment by lburgazzoli** [comment]
I'm unsure how to fix it as dependencies with same GAV are conflated by gradle, see https://discuss.gradle.org/t/dependencies-same-gav-but-different-type-classifier/20112.

As workaround you can create different configurations, like:

```groovy
configurations {
    karaf1
    karaf2
}

dependencies {
    karaf1 "ca.uhn.hapi.fhir:hapi-fhir-testpage-overlay:2.0:classes"
    karaf2 "ca.uhn.hapi.fhir:hapi-fhir-testpage-overlay:2.0@war"
}

feature {
    name = "feature-1"
    configurations "karaf1", "karaf2"
}
```

**Comment by lburgazzoli** [comment]
@yrashk 

I've committed some changes related to this issue but I'm not sure to have time to test it properly this week, if you have time, can you take a look ? You need to build the plugin from sources.
