### ISSUE TITLE
resolve dependencies from gradle m2 cache not maven local cache

### ISSUE THREAD

**Issue by u650080** [lburgazzoli/gradle-karaf-plugin#35]
Hi, we are trying to use your plugin with thirdparty dependencies resolving from our local gradle cache and not the maven local cache. We use artifactory resolver to populate the gradle cache and not mavenLocal.

Can this be configured in your karaf plugin ? How can we achieve this by setting the resolution dependency location to the gradle cache which contains all of our dependencies.

Gradle error trying to resolve thirdparty dependency from local maven cache:

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':runtime'.
> Could not find org.apache.sshd:sshd-core:1.3.0.
  Searched in the following locations:
      file:/home/vagrant/.m2/repository/org/apache/sshd/sshd-core/1.3.0/sshd-core-1.3.0.pom
      file:/home/vagrant/.m2/repository/org/apache/sshd/sshd-core/1.3.0/sshd-core-1.3.0.jar

Can we configure the plugin to look at the gradle cache to resolve these dependencies to resolve this issue ? 

Thanks

**Comment by lburgazzoli** [comment]
The plugin relies on gradle to resolve the dependencies so everything that gradle can resolve should be resolvable by the plugin. 

Are your dependencies listed using gradle dependencies  ?

**Comment by u650080** [comment]
Yes, this is from of build.gradle
dependencies {
    compile 'org.apache.sshd:sshd-core:1.3.0'
    compile 'org.apache.servicemix.bundles:org.apache.servicemix.bundles.oro:2.0.8_6'
    compile 'org.bouncycastle:bcpkix-jdk15on:1.55'
    
    testCompile 'junit:junit:4.11'
    testCompile 'org.mockito:mockito-all:1.10.19'
}
And we can see those in gradle cache

**Comment by u650080** [comment]
# this is the example of gradle file:
buildscript {
    repositories {
        maven {
            url = "http://orbw-artifactory.ca.alcatel-lucent.com:8081/artifactory/plugins-release"
        }

    }
    dependencies {
        classpath 'com.github.lburgazzoli:gradle-karaf-plugin:0.0.+'

    }
}

apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'com.github.lburgazzoli.karaf'

dependencies {

    compile 'org.apache.sshd:sshd-core:1.3.0'
    compile 'org.apache.servicemix.bundles:org.apache.servicemix.bundles.oro:2.0.8_6'
    compile 'org.bouncycastle:bcpkix-jdk15on:1.55'
    compile 'org.apache.commons:commons-lang3:3.3' 
    testCompile 'junit:junit:4.11'
    testCompile 'org.mockito:mockito-all:1.10.19'
}
karaf {
    features {

        feature {
            name        = 'nokia-registry'
            description = 'Nokia :: Discovery'

        }
    }
    kar {
        
    }
}
defaultTasks 'clean', 'build'




**This is out when we run gradle:**
Download http://orbw-artifactory.ca.alcatel-lucent.com:8081/artifactory/plugins-release/com/github/lburgazzoli/gradle-karaf-plugin/0.0.44/gradle-karaf-plugin-0.0.44.jar
Download http://orbw-artifactory.ca.alcatel-lucent.com:8081/artifactory/plugins-release/org/ops4j/pax/url/pax-url-aether/2.5.1/pax-url-aether-2.5.1.jar
Download http://orbw-artifactory.ca.alcatel-lucent.com:8081/artifactory/plugins-release/org/ops4j/pax/url/pax-url-aether-support/2.5.1/pax-url-aether-support-2.5.1.jar
Download http://orbw-artifactory.ca.alcatel-lucent.com:8081/artifactory/plugins-release/org/slf4j/jcl-over-slf4j/1.6.6/jcl-over-slf4j-1.6.6.jar
Download http://orbw-artifactory.ca.alcatel-lucent.com:8081/artifactory/plugins-release/org/eclipse/aether/aether-impl/1.0.2.v20150114/aether-impl-1.0.2.v20150114.jar
Download http://orbw-artifactory.ca.alcatel-lucent.com:8081/artifactory/plugins-release/org/slf4j/slf4j-api/1.6.6/slf4j-api-1.6.6.jar
Download http://orbw-artifactory.ca.alcatel-lucent.com:8081/artifactory/plugins-release/org/eclipse/aether/aether-api/1.0.2.v20150114/aether-api-1.0.2.v20150114.jar
Download http://orbw-artifactory.ca.alcatel-lucent.com:8081/artifactory/plugins-release/org/eclipse/aether/aether-spi/1.0.2.v20150114/aether-spi-1.0.2.v20150114.jar
Download http://orbw-artifactory.ca.alcatel-lucent.com:8081/artifactory/plugins-release/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
:clean
:generateFeatures

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':runtime'.
> Cannot resolve external dependency org.apache.sshd:sshd-core:1.3.0 because no repositories are defined.
  Required by:
      com.nokia.nsp.mvm:test:17.6.0-rel.0-SNAPSHOT
> Cannot resolve external dependency org.apache.servicemix.bundles:org.apache.servicemix.bundles.oro:2.0.8_6 because no repositories are defined.
  Required by:
      com.nokia.nsp.mvm:test:17.6.0-rel.0-SNAPSHOT
> Cannot resolve external dependency org.bouncycastle:bcpkix-jdk15on:1.55 because no repositories are defined.
  Required by:
      com.nokia.nsp.mvm:test:17.6.0-rel.0-SNAPSHOT
> Cannot resolve external dependency org.apache.commons:commons-lang3:3.3 because no repositories are defined.
  Required by:
      com.nokia.nsp.mvm:test:17.6.0-rel.0-SNAPSHOT

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by lburgazzoli** [comment]
Can you list your maven repo also outside the buildscript ?

**Comment by u650080** [comment]
I tried with version 0.0.17 and it worked, we are using gradle 2.11

**Comment by lburgazzoli** [comment]
did you test with the repo listed also outside buildscript ?

**Comment by u650080** [comment]
When building with plugin version 0.44 (or 0.19+) the local maven repo is empty ~/.m2/repository

Can you try with an empty .m2 directory with the example we provided, you will see that it works correctly with older version 0.17

**Comment by u650080** [comment]
Tried it defining maven repo outside of the buildscript section and your plugin latest version 0.44 is now working.

Thanks for your help!

**Comment by lburgazzoli** [comment]
I will in the coming days but in the meantime can you perform the task I've asked:

- give me the output of gradle dependencies
- test by defining dependencies repository outside the buildscript block
