### ISSUE TITLE
copy config file in kar with wrong path 

### ISSUE THREAD

**Issue by u650080** [lburgazzoli/gradle-karaf-plugin#37]
Hi ,
when I try to use your example for config file :
// Add configFile entry and copy a local file to the kar repository
            configFile {
                filename = "/etc/hazelcast-clustered.xml"
                file     = file("etc/hazelcast-clustered-defaults.xml")
                uri      = "mvn:org.apache.karaf.cellar/apache-karaf-cellar/${project.version}/xml/hazelcast-clustered"
            }
 
There is an issue when the config file is copied to kar, it creates the directory :   repository/mvn:org/apache/karaf/cellar/apache-karaf-cellar/0.0.1  which  this should be repository/org/apache/karaf/cellar/apache-karaf-cellar/0.0.1

**Comment by u650080** [comment]
Had a look at your code, found the issue and here is a fix:

 gradle-karaf-plugin/src/main/groovy/com/github/lburgazzoli/gradle/plugin/karaf/kar/KarafKarTask.groovy

Function protected void copy() { (line 44)
Diff (lines 70-87):

            feature.configFiles.each {
                if (it.filename && it.uri && it.file) {
                    def dep = MvnProtocolParser.parse(it.uri)
                    if (dep) {
                        def(protocol, groupArtifact) = dep.group.tokenize(':')
                        copy(
                            it.file,
                            asKarPath(
                                root,
                                "${groupArtifact.replaceAll("\\.", "/")}/${dep.name}/${dep.version}",
                                dep.hasClassifier()
                                    ? "${dep.name}-${dep.version}-${dep.classifier}.${dep.type}"
                                    : "${dep.name}-${dep.version}.${dep.type}"
                            )
                        )
                    }
                }
            }
        }

Can you take a look at my change and commit to master and release new version with the fix  ?
Thanks

**Comment by lburgazzoli** [comment]
can you open a pr ?

**Comment by u650080** [comment]
no , I can't

**Comment by u650080** [comment]
I did it ...

**Comment by lburgazzoli** [comment]
Do you mind having a look at MvnProtocolParser as well ? 
Looks like it's behaving not as I'd expect

**Comment by u650080** [comment]
I changed MvnProtocolParser file to remove protocol portion from group id

**Comment by u650080** [comment]
but do you use this MvnProtocolParser  to generate feature files?  you need to add protocol(mvn:) in feature file.

**Comment by lburgazzoli** [comment]
I've released a new snapshot using a different solution so if the pax-url changes how it render the group id (i.e. it removes the mvn: prefix), the plugin should work without changes, can you test it ?

https://oss.sonatype.org/content/repositories/snapshots/com/github/lburgazzoli/gradle-karaf-plugin/0.0.45-SNAPSHOT/

**Comment by u650080** [comment]
it worked very well, when do you release it?
Thanks

**Comment by lburgazzoli** [comment]
Hope tomorrow

**Comment by lburgazzoli** [comment]
v0.0.45 has been released, already available on gradle plugins and soon on maven central.

**Comment by u650080** [comment]
thanks
