### ISSUE TITLE
whitelisting bundles in feature

### ISSUE THREAD

**Issue by tonit** [lburgazzoli/gradle-karaf-plugin#43]
Maybe its just my gradle noob status but shouldn't it be really simple to only pick a handful of subprojects to be included in your feature.xml.
Right now, i need to maintain a quite large blacklist of bundles like so:

> bundle(':bundleA') {  include = false }
> bundle(':bundleB') {  include = false }
> ..
See, in my case the blacklist is quite large where the whitelist (read below) would be small. Also there is the danger that bundles get included at some point without changing the gradle build file. This would not happen if i could hand-pick the sub projects.

But i would like to do that:
> bundle(':*') {  include = false }
> bundle(':bundleC') {  include = true }

Even the that first "*" line might rather not be needed if there is a way to say "addSubprojects=false".
Again, probably done via gradle magic, but i don't know how yet. Would be cool to have it in the plugin. ;)

**Comment by lburgazzoli** [comment]
As today the plugin relies on gradle configurations so if you need to customize what the plugin uses to make the features/kar, you can create a new configuration and use it, something like:

```groovy
configurations {
    myConfig
}

dependencies {
    myConfig project(':my-project')
}

karaf {
    features {
        feature {
            configuration 'myConfig'
        }
    }
}
```

This gives you the all the power gradle has when composing configurations.

Is that what you are looking for ?

**Comment by tonit** [comment]
i see.. let me try. Thanks for your quick response!

**Comment by lburgazzoli** [comment]
Of course I can evaluate to add some more logic but I want to reuse gradle's stuffs as much as possible :)

**Comment by lburgazzoli** [comment]
@tonit can I close this issue ?

**Comment by tonit** [comment]
sorry, actually forgot about it. But I think we managed it back then. Thanks!
