### ISSUE TITLE
Add regular exception / ant style pattern matching support for bundles 

### ISSUE THREAD

**Issue by ieugen** [lburgazzoli/gradle-karaf-plugin#49]
Hello, 

I'm using the plugin to build a feature for Apache Oak and Apache Sling. Some bundles from some features need to be marked as dependencies. 

It would be easier if we could do that using an regular expression or event better ant style pattern matching (ant patterns are much simpler). 

For 
````
    jackrabbitSling "commons-codec:commons-codec:1.10"
    jackrabbitSling "commons-collections:commons-collections:3.2.2"
    jackrabbitSling "commons-fileupload:commons-fileupload:1.3.2"
    jackrabbitSling "commons-io:commons-io:2.5"
    jackrabbitSling "commons-lang:commons-lang:2.6"
````

It would be nice to have: 
````
            bundle('commons-*') {
                attribute 'dependency', 'true'
            }
````

[1] https://ant.apache.org/manual/dirtasks.html
[2] https://github.com/azagniotov/ant-style-path-matcher

**Comment by lburgazzoli** [comment]
Could you try-out the latest 0.0.47-SNAPSHOT ?

**Comment by ieugen** [comment]
How can I try it? is it published somewhere like bintray? Should I build it locally?

**Comment by ieugen** [comment]
By the way, I use gradle git [1] to make releases. Bellow is a sample configuration. 

You can release with: 

````
./gradlew release -Prelease.scope=major -Prelease.stage=final
````

`````
plugins {
    id "com.jfrog.bintray" version "1.7.3"
    id 'maven-publish'
    id "org.ajoberstar.grgit" version "1.7.1"
    id 'org.ajoberstar.release-base' version '1.7.1'
}

import org.ajoberstar.gradle.git.release.opinion.Strategies

release {
    versionStrategy Strategies.SNAPSHOT
    versionStrategy Strategies.FINAL

    defaultVersionStrategy Strategies.SNAPSHOT
}
`````

[1] https://github.com/ajoberstar/gradle-git/wiki/Release-Plugins

**Comment by lburgazzoli** [comment]
Yeah, it is on OSS Sonatype 

https://oss.sonatype.org/content/repositories/snapshots/com/github/lburgazzoli/gradle-karaf-plugin/

**Comment by ieugen** [comment]
Works great. Thanks. I would like to use it soon to make a first release of the features project. When do you think you can make a release?

**Comment by lburgazzoli** [comment]
It is on gradle plugin portal now

https://plugins.gradle.org/plugin/com.github.lburgazzoli.karaf
