### ISSUE TITLE
capability generation only allows one service capability, which is wrong

### ISSUE THREAD

**Issue by tonit** [lburgazzoli/gradle-karaf-plugin#55]
Capabilities can be numerous per feature, and they are not required to be unique by type (e.g. osgi.service). You can have many service capabilities in a feature.

**Comment by tonit** [comment]
will add a pr on this

**Comment by tonit** [comment]
thanks, @lburgazzoli

**Comment by lburgazzoli** [comment]
A new 0.0.49 should be out

**Comment by tonit** [comment]
awesome: https://plugins.gradle.org/plugin/com.github.lburgazzoli.karaf
