### ISSUE TITLE
ServiceMix (Karaf) Custom Distribution

### ISSUE THREAD

**Issue by realPyR3X** [lburgazzoli/gradle-karaf-plugin#62]
Hello,

I'm looking for an easy to create a custom distribution of Apache ServiceMix preconfigured with my application packaged as a KAR. I have a Gradle multi project where the root has a configuration to download and expand a clean copy of Apache ServiceMix. Each subproject inherits from a common.gradle which uses 'org.dm.bundle' to generate OSGi bundles from each subproject. The idea is that each subproject would generate an OSGi bundle along with it's transitive dependencies (defined in the dependency block and wrapped with bnd), and layed out in maven repository format. Then I'd like to use this plug-in to generate a features xml and ultimately package the KAR file for deployment in the custom distribution.

I'm not sure if I'm in the right place to be asking this but any pointers/help to solve the above would be greatly appreciated. If the answer is I simply need to write something myself I will.

Thanks,

-Charlie

**Comment by lburgazzoli** [comment]
It sounds possible but I can't tell without a sample, do you have one ?

**Comment by realPyR3X** [comment]
[example.zip](https://github.com/lburgazzoli/gradle-karaf-plugin/files/1606809/example.zip)
Hello,

I've attached some build configuration files the layout of the project would be the following:

example/
---- build.gradle
---- settings.gradle
---- common.gradle
---- example-core/
           -build.gradle
---- example-security/
           -build.gradle

The root project would download a clean servicemix and expand it to build/servicemix. Ideally each subproject would generate artifacts (bundles) along with their transitive dependencies (already wrapped with bnd) and layt it out in the maven repository format in build/servicemix/system along with other configuration files for provisioning. I was initially using the 'run-osgi' plugin to automatically wrap third party jars and create the artifacts to put in the 'deploy' directory but this is a sub-optimal design. Anything you could help with would be great.

Thanks,

-Charlie

**Comment by realPyR3X** [comment]
I guess what I'm really looking for is if it's possible when defining a feature in the root project to the set the configuration to a subprojects dependencies.
