### ISSUE TITLE
KAR generation does properly package dependencies with classifiers.

### ISSUE THREAD

**Issue by realPyR3X** [lburgazzoli/gradle-karaf-plugin#65]
It would seem that maven dependencies with classifiers are not properly picked up and packaged in the output KAR file. I have the following dependencies that are not being packaged.

dependencies {
  implementation 'com.github.jnr:jffi:1.2.18:complete'
  implementation 'com.github.jnr:jffi:1.2.18:native'
}

**Comment by lburgazzoli** [comment]
Fixed by https://github.com/lburgazzoli/gradle-karaf-plugin/pull/67
