### ISSUE TITLE
Unable to install "self" as a bundle

### ISSUE THREAD

**Issue by eximius313** [lburgazzoli/gradle-karaf-plugin#70]
I'd like to create feature, that installs bundle, which is the output of `./gradle build`
In features.xml I'd use:
```
<feature name="my-bundle" version="0.0.1">
    <bundle>mvn:com.my.company/my.bundle/0.0.1</bundle>
</feature>
```
But `gradle-karaf-plugin` ignores anything that is not in `dependencies` section, so this:
```
feature {
  name = 'my-bundle'
  bundle 'com.my.company:my.bundle:0.0.1'
}
```
generates just:
`  <feature name="my-bundle" version="0.0.1-SNAPSHOT" />`

**Comment by lburgazzoli** [comment]
this is expected, the plugins relies on gradle's dependencies set-up.
the `bundle` instruction you can use in the `feture` block is used to customize the given bundle

**Comment by eximius313** [comment]
so how I can achieve what I want and produce:
```
<feature name="my-bundle" version="0.0.1">
    <bundle>mvn:com.my.company/my.bundle/0.0.1</bundle>
</feature>
```
?

**Comment by lburgazzoli** [comment]
You can create a custom configuration in gradle and you can add your dependencies there, if you look at the main readme you can see a number of configurations, like hazelcast and related dependencies added to those configurations. then you can see that the hazelcast configuration is used in the hazelcast feature

**Comment by eximius313** [comment]
1) I've read readme, but it contains a lot of noise and is not clear
2) I've modified my build.gradle like this:
```
plugins {
  id 'com.github.lburgazzoli.karaf' version '0.0.49'
}
repositories {
  mavenLocal()
}
configurations {
    archives
    api
    common
}
dependencies {
  api "com.my.company:my.api:$version"
  common "com.my.company:my.common:$version"
}
karaf {
    features {
        xsdVersion  = '1.2.0'
        version     = '1.0.0.'
        description = 'Karaf features'
        includeProject = false
        feature {
            name        = 'my-api'
            configuration 'api'
            bundle 'my.api'
        }
        feature {
            name        = 'my-common'
            configuration 'common'
            bundle 'my.common'
        }
}
```
but they're still empty

**Comment by lburgazzoli** [comment]
need to test, but do your deps exists and available somewhere in a repository ?

**Comment by eximius313** [comment]
yes, in maven local

**Comment by lburgazzoli** [comment]
need to check

**Comment by eximius313** [comment]
Ok, I've cleaned the build and now the configuration above indeed generates required bundles.
I'm closing this issue, but if you could make readme more clear (reduce unnecessay noise, leave only whats really needed to demonstrate the feature and describe what configurations do - it would be great).
Thank you in advance
