### ISSUE TITLE
Missing repository folder after the creation of kar file

### ISSUE THREAD

**Issue by eschizoid** [lburgazzoli/gradle-karaf-plugin#9]
KAR file should have the following folder strcuture:

````
features.kar
    - META-INF
    - repository
````

The final artifact does not have the repository folder and can't be deploy in karaf.

**Comment by lburgazzoli** [comment]
Fix available in v0.0.16

**Comment by eschizoid** [comment]
@lburgazzoli Thanks. Working fine with version `0.0.16`
